openapi: 3.0.0
info:
  title: IPFS RPC Add Ls API
  version: v0
  description: 'When a Kubo IPFS node is running as a daemon, it exposes an HTTP RPC API that allows you to control the node and run the same commands you can from the command line.


    In many cases, using this RPC API is preferable to embedding IPFS directly in your program — it allows you to maintain peer connections that are longer lived than your app and you can keep a single IPFS node running instead of several if your app can be launched multiple times. In fact, the `ipfs` CLI commands use this RPC API when operating in online mode.'
  x-providerName: IPFS
  x-logo:
    url: https://raw.githubusercontent.com/ipfs/ipfs-docs/55fe8bc6a53ba3b9023951fb4b432efbbc81fba5/docs/.vuepress/public/images/ipfs-logo.svg
servers:
- description: Local IPFS node
  url: http://localhost:5001
- description: Local IPFS node
  url: http://127.0.0.1:5001
- description: Infura hosted IPFS node
  url: https://ipfs.infura.io:5001
tags:
- name: Ls
paths:
  /api/v0/ls:
    post:
      operationId: ls
      description: List directory contents for Unix filesystem objects.
      externalDocs:
        url: https://docs.ipfs.tech/reference/kubo/rpc/#api-v0-ls
      parameters:
      - name: arg
        in: query
        description: The path to the IPFS object(s) to list links from.
        required: true
        schema:
          type: string
      - name: headers
        in: query
        description: Print table headers (Hash, Size, Name).
        schema:
          type: boolean
      - name: resolve-type
        in: query
        description: Resolve linked objects to find out their types.
        schema:
          type: boolean
          default: true
      - name: size
        in: query
        description: Resolve linked objects to find out their file size.
        schema:
          type: boolean
          default: true
      - name: stream
        in: query
        description: Enable experimental streaming of directory entries as they are traversed.
        x-experimental: true
        schema:
          type: boolean
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                Objects:
                - Hash: <string>
                  Links:
                  - Hash: <string>
                    Name: <string>
                    Size: <uint64>
                    Target: <string>
                    Type: <int32>
      tags:
      - Ls
externalDocs:
  url: https://docs.ipfs.tech/reference/kubo/rpc/
