openapi: 3.0.0
info:
  title: IPFS RPC Add Multibase API
  version: v0
  description: 'When a Kubo IPFS node is running as a daemon, it exposes an HTTP RPC API that allows you to control the node and run the same commands you can from the command line.


    In many cases, using this RPC API is preferable to embedding IPFS directly in your program — it allows you to maintain peer connections that are longer lived than your app and you can keep a single IPFS node running instead of several if your app can be launched multiple times. In fact, the `ipfs` CLI commands use this RPC API when operating in online mode.'
  x-providerName: IPFS
  x-logo:
    url: https://raw.githubusercontent.com/ipfs/ipfs-docs/55fe8bc6a53ba3b9023951fb4b432efbbc81fba5/docs/.vuepress/public/images/ipfs-logo.svg
servers:
- description: Local IPFS node
  url: http://localhost:5001
- description: Local IPFS node
  url: http://127.0.0.1:5001
- description: Infura hosted IPFS node
  url: https://ipfs.infura.io:5001
tags:
- name: Multibase
paths:
  /api/v0/multibase/decode:
    post:
      operationId: multibase/decode
      description: Decode multibase string
      externalDocs:
        url: https://docs.ipfs.tech/reference/kubo/rpc/#api-v0-multibase-decode
      parameters: []
      requestBody:
        description: Argument `encoded_file` is of file type. This endpoint expects one or several files (depending on the command) in the body of the request as 'multipart/form-data'.
        content: {}
      responses:
        '200':
          description: Successful response
      tags:
      - Multibase
  /api/v0/multibase/encode:
    post:
      operationId: multibase/encode
      description: Encode data into multibase string
      externalDocs:
        url: https://docs.ipfs.tech/reference/kubo/rpc/#api-v0-multibase-encode
      parameters:
      - name: b
        in: query
        description: multibase encoding.
        schema:
          type: string
          default: base64url
      requestBody:
        description: Argument `file` is of file type. This endpoint expects one or several files (depending on the command) in the body of the request as 'multipart/form-data'.
        content: {}
      responses:
        '200':
          description: Successful response
      tags:
      - Multibase
  /api/v0/multibase/list:
    post:
      operationId: multibase/list
      description: List available multibase encodings.
      externalDocs:
        url: https://docs.ipfs.tech/reference/kubo/rpc/#api-v0-multibase-list
      parameters:
      - name: prefix
        in: query
        description: also include the single letter prefixes in addition to the code.
        schema:
          type: boolean
      - name: numeric
        in: query
        description: also include numeric codes.
        schema:
          type: boolean
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
              - Code: <int>
                Name: <string>
      tags:
      - Multibase
  /api/v0/multibase/transcode:
    post:
      operationId: multibase/transcode
      description: Transcode multibase string between bases
      externalDocs:
        url: https://docs.ipfs.tech/reference/kubo/rpc/#api-v0-multibase-transcode
      parameters:
      - name: b
        in: query
        description: multibase encoding.
        schema:
          type: string
          default: base64url
      requestBody:
        description: Argument `encoded_file` is of file type. This endpoint expects one or several files (depending on the command) in the body of the request as 'multipart/form-data'.
        content: {}
      responses:
        '200':
          description: Successful response
      tags:
      - Multibase
externalDocs:
  url: https://docs.ipfs.tech/reference/kubo/rpc/
