openapi: 3.0.0
info:
  title: IPFS RPC Add Get API
  version: v0
  description: 'When a Kubo IPFS node is running as a daemon, it exposes an HTTP RPC API that allows you to control the node and run the same commands you can from the command line.


    In many cases, using this RPC API is preferable to embedding IPFS directly in your program — it allows you to maintain peer connections that are longer lived than your app and you can keep a single IPFS node running instead of several if your app can be launched multiple times. In fact, the `ipfs` CLI commands use this RPC API when operating in online mode.'
  x-providerName: IPFS
  x-logo:
    url: https://raw.githubusercontent.com/ipfs/ipfs-docs/55fe8bc6a53ba3b9023951fb4b432efbbc81fba5/docs/.vuepress/public/images/ipfs-logo.svg
servers:
- description: Local IPFS node
  url: http://localhost:5001
- description: Local IPFS node
  url: http://127.0.0.1:5001
- description: Infura hosted IPFS node
  url: https://ipfs.infura.io:5001
tags:
- name: Get
paths:
  /api/v0/get:
    post:
      operationId: get
      description: Download IPFS objects.
      externalDocs:
        url: https://docs.ipfs.tech/reference/kubo/rpc/#api-v0-get
      parameters:
      - name: arg
        in: query
        description: The path to the IPFS object(s) to be outputted.
        required: true
        schema:
          type: string
      - name: output
        in: query
        description: The path where the output should be stored.
        schema:
          type: string
      - name: archive
        in: query
        description: Output a TAR archive.
        schema:
          type: boolean
      - name: compress
        in: query
        description: Compress the output with GZIP compression.
        schema:
          type: boolean
      - name: compression-level
        in: query
        description: The level of compression (1-9).
        schema:
          type: integer
      - name: progress
        in: query
        description: Stream progress data.
        schema:
          type: boolean
          default: true
      responses:
        '200':
          description: Successful response
      tags:
      - Get
externalDocs:
  url: https://docs.ipfs.tech/reference/kubo/rpc/
